version: '3.8'

services:
  audio-analyzer:
    build:
      context: .
    image: audio-analyzer:latest       
    container_name: audio-analyzer     
    volumes:
      - ./:/app
    networks:
      - npm-network                  

networks:
  npm-network:
    external: true
