version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped
    command: python server.py --host 0.0.0.0
    networks:
      - audio-network

networks:
  audio-network:
    driver: bridge
